blank_issues_enabled: false
contact_links:
  - name: 💬 Preguntas y discusiones
    url: https://github.com/zeluizr/palta/discussions
    about: Para preguntas generales usa las discusiones
  - name: 📦 npmjs.com
    url: https://www.npmjs.com/package/@zeluizr/palta
    about: Ver el paquete en npm
  - name: 📖 Wiki
    url: https://github.com/zeluizr/palta/wiki
    about: Guía de uso, referencia de API y cómo contribuir
